### ISSUE TITLE
Header not Rendering on Mobile

### ISSUE THREAD

**Issue by JeffThorslund** [JeffThorslund/Bent-Shaft-Maps#45]
/client/src/components/interface/Putin.js not rendering on mobile.

```
<div className="header">
//This div is not rendering on mobile.
</div>
```

Device Type: Iphone XR
URL: https://www.bentshaftmaps.com/ottawa-river

Bug:
![image](https://user-images.githubusercontent.com/54057907/85357101-9d1ec400-b4de-11ea-95bb-8623b49bd4d1.png)

Desired result:
![image](https://user-images.githubusercontent.com/54057907/85357020-75c7f700-b4de-11ea-8609-65c45c14aada.png)

**Comment by oliviaperryman** [comment]
10/10 face for Em. But if she's using Safari I wouldn't even bother fixing it. Tell her to use chrome. I can't even repro the bug

**Comment by JeffThorslund** [comment]
That is the answer I wanted to hear.
