### ISSUE TITLE
Rework "addRapid" Command Line Tool

### ISSUE THREAD

**Issue by JeffThorslund** [JeffThorslund/Bent-Shaft-Maps#6]
The "addRapid" command line tool creates an instance of a rapid for the developer to start working on. It is written in Node.js and has two functions.

Found at src/tools/CLI/addRapid

1.**CreateBasemap** - Copies file `src/river-data/my-river-template/basemaps/TemplateRapid.js`, injects "Rapid Name" into it, writes it to `src/river-data/[river-name]/basemaps/[RapidName].js`.
2.**Append Data File** - Adds a template object as a member to data array in data.js with basic information like name.

Note: This tool has to be run from inside the `src/river-data/[river-name]` location in the terminal as pathing is all  relative to current location. Absolute pathing would require a information about what rapid the rapid being created is a part of. This is probably a good idea, to eliminate the user from having to switch terminal paths before running the AddRapid command. 

This tool uses commented ids, similar to #5. A better way forward should be found which is less likely to cause accidental errors. The solution to this will likely be similar to #5.

**Comment by oliviaperryman** [comment]
This is deprecated

**Comment by JeffThorslund** [comment]
Replaced by form based UI.
