### ISSUE TITLE
Project Logo Design

### ISSUE THREAD

**Issue by JeffThorslund** [JeffThorslund/Bent-Shaft-Maps#7]
Design a "Wet Exit" logo to be used on the GitHub README, the favicon, and possibly the live site. They can be the same, or different but should have the same style/feel. Capture the spirit of whitewater kayaking in a simple graphic!

**Comment by JeffThorslund** [comment]
![image](https://user-images.githubusercontent.com/54057907/81212658-2e73be80-8fa3-11ea-9a93-a1a6298f2996.png)

First logo design. Using Waka Kayak shape and "compass" design elements. Consider changing colors in future revision.

**Comment by oliviaperryman** [comment]
![compass-kayak](https://user-images.githubusercontent.com/11139135/81479623-4c832e00-91f2-11ea-9afd-07ebc9c36cc5.png)

**Comment by JeffThorslund** [comment]
This is SO SO cool. Did you try it with a 2 color scheme?

**Comment by JeffThorslund** [comment]
![HeaderLogo](https://user-images.githubusercontent.com/54057907/84183489-fce68b00-aa59-11ea-89ac-5d4e1b448ae2.png)

Final Design.
