### ISSUE TITLE
Fix Auth Component

### ISSUE THREAD

**Issue by bekatru** [JeffThorslund/Bent-Shaft-Maps#86]
**Console throws two errors:**

>First one is an easy fix.
![image](https://user-images.githubusercontent.com/70205327/102692831-206b6900-4227-11eb-8863-f457b1d2a485.png)
This caused by the lack of `id` value in `AuthInterface.registrationFormData.buttonData.id`

>Possible solution:
![image](https://user-images.githubusercontent.com/70205327/102692904-c7500500-4227-11eb-9ff0-118a9a054695.png)
__________________________________________________________________________________________________________________________________

>Second one is more confusing.
![image](https://user-images.githubusercontent.com/70205327/102692368-e187e400-4223-11eb-8631-902e550cd340.png)
  This one refers to unrecognized prop `controlId`, which is a Bootstrap accessibility feature. 
  At least, that's what I figured out while [researching](https://react-bootstrap.github.io/components/forms).
  Nevertheless, this component doesn't seem to be using Bootstrap at all. 

_This leads to another problem._

>In `~\user\authentication\FormArea.js`,
![image](https://user-images.githubusercontent.com/70205327/102692576-44c64600-4225-11eb-97c0-15415b16d86e.png)
  Form groups are composed with simple `<div/>` tags. The outcome is obvious.
  Supposedly, it should be built with BS components, such as `Form.Group` `Form.Text` etc. Or something else...

>Possible solution:
Import Bootstrap and apply its' components.
Otherwise, we'll have to... I don't know :)
________________________________________________________________________________________________________________________________________
Lastly,
![image](https://user-images.githubusercontent.com/70205327/102693050-be136800-4228-11eb-9a44-d26e4c49bc5d.png)
![image](https://user-images.githubusercontent.com/70205327/102693091-0b8fd500-4229-11eb-99cf-5f921cfd5feb.png)
>When choosing credentials from the dropdown, autofill works odd.
I guess because of the same `name` attribute.
________________________________________________________________________________________________________________________________________

I am gonna leave it as it is right now, just in case you have some other plans for it.
Nonetheless, I am confident I can fix it. And make it clean, beautiful and working.:)
If you give me a permission for I'll get it done and send a PR.

**Comment by bekatru** [comment]
I am confident I can fix the Auth component. And make it clean and beautiful :)
If you give me a permission for I'll get it done and send a PR.

**Comment by JeffThorslund** [comment]
Ya that all sounds good. Go for it. I fixed the "Register Button" thing in the last merge. 

Can you explain what the current login behaviour is, and what you think the intended behaviour is?

**Comment by JeffThorslund** [comment]
@bekatru Adding buttons to auto fill different login cases would be super useful! You can reference how it was done before.
