### ISSUE TITLE
Add and Remove Points from Eddy in Test Environment

### ISSUE THREAD

**Issue by JeffThorslund** [JeffThorslund/Bent-Shaft-Maps#96]
This will use similar reducers as the add/delete line point functionality, but will have to take into consideration a few extra cases.

- User might want to delete the origin point (M)...what happens then?? 
- When a user adds a new point, where does it go? At a preset x,y value? Between 2 existing points?

**Comment by bekatru** [comment]
I have been thinking about this and I came up with an idea. 
I asked my self, "Do our users really need to have an ability to add points to eddys?"
Think about this for a minute.

Two points eddy can give you a circle, an oval/ellipse;
![image](https://user-images.githubusercontent.com/70205327/104176280-0ed94380-5418-11eb-9e8d-fb5d111bfa2b.png)
Or even some more complex shapes.
![image](https://user-images.githubusercontent.com/70205327/104176395-38926a80-5418-11eb-8b3a-a282d6d7ebbb.png)
 
Then three points can give you a heart shape or a moon shape:
![image](https://user-images.githubusercontent.com/70205327/104176474-5b248380-5418-11eb-8320-0d8319bbd061.png)
Four point will allow you to do a cross shape, five point - star shape.

That's great, but how many eddys are star shaped?
I am not a kayaker, but my intuition says me that eddys are usually circles. In some cases hearts, right? 

I think if we just make all eddys three pointed it would be more than enough. Users would be able to map any kind of eddy out.

Does it make sense?

**Comment by JeffThorslund** [comment]
Its a good thought. I think that the oval shape would cover about half of the use cases, but there are still lots of eddies that have strange complex oval-type shapes. Not necessarily "star" shapes with sharp points but smooth bean-like shapes. I thinks its important that the eddy is able to easily cover the entire eddy on the map, and not leave out sections of it because the user is unable to add more points. 

We also already have a point adding function for the lines that we can use, it will just be a bit more complicated.

I still think being able to add and remove points is the way to go, we just need to find a way to make it intuive for the user, and intuitive for our code.
